In [1]:
import json
from matplotlib import pyplot as plt
from collections import defaultdict
from sklearn import linear_model
import numpy
import random
import gzip
import math
import sklearn
import statistics

In [2]:
def assertFloat(x): # Checks that an answer is a float
    assert type(float(x)) == float

def assertFloatList(items, N):
    assert len(items) == N
    assert [type(float(x)) for x in items] == [float]*N

In [139]:
f = open("young_adult_10000.json")
dataset = []
for l in f:
    dataset.append(json.loads(l))

In [4]:
len(dataset)

10000

In [23]:
answers = {} # Put your answers to each question in this dictionary

In [8]:
dataset[0]

{'user_id': '8842281e1d1347389f2ab93d60773d4d',
 'book_id': '2767052',
 'review_id': '248c011811e945eca861b5c31a549291',
 'rating': 5,
 'review_text': "I cracked and finally picked this up. Very enjoyable quick read - couldn't put it down - it was like crack. \n I'm a bit bothered by the lack of backstory of how Panem and the Hunger Games come about. It is just kind of explained away in a few paragraphs and we are left to accept this very strange world where teenagers are pitted into an arena each year to kill each other? I was expecting it because I've seen Battle Royale, but I would have appreciated knowing more of the backstory of how the world could have come into such a odd state. \n I suppose what makes a book like this interesting is thinking about the strategy of it all. The players are going to be statistically encouraged to band together because they will last longer that way, but by definition of course any partnership will be broken, and the drama of how that unfolds is alw

In [9]:
### Question 1

In [13]:
def feature(datum):
    feat = datum['review_text'].count("!")
    return [1] + [feat]

In [14]:
X = [feature(d) for d in dataset]
Y = [d['rating'] for d in dataset]
theta,residuals,rank,s = numpy.linalg.lstsq(X, Y, rcond=None)
theta

array([3.68853304, 0.07109019])

In [17]:
model = sklearn.linear_model.LinearRegression(fit_intercept=False)
model.fit(X, Y)
Theta = model.coef_
Theta

array([3.68853304, 0.07109019])

In [21]:
y_pred = model.predict(X)
sse = sum([x**2 for x in (Y - y_pred)])
mse = sse / len(Y)
mse

1.5231747404538247

In [24]:
answers['Q1'] = [Theta[0], Theta[1], mse]

In [25]:
assertFloatList(answers['Q1'], 3) # Check the format of your answer (three floats)

In [ ]:
### Question 2

In [26]:
def feature(datum):
    feat = [1] 
    feat.append(len(datum['review_text'])) 
    feat.append(datum['review_text'].count("!")) 
    return feat

In [33]:
X = numpy.array([feature(d) for d in dataset])
Y = [d['rating'] for d in dataset]

In [34]:
model = sklearn.linear_model.LinearRegression(fit_intercept=False)
model.fit(X, Y)
Theta = model.coef_
Theta

array([ 3.71751281e+00, -4.12150653e-05,  7.52759173e-02])

In [35]:
y_pred = model.predict(X)
sse = sum([x**2 for x in (Y - y_pred)])
mse = sse / len(Y)
mse

1.5214029246165857

In [36]:
answers['Q2'] = [Theta[0], Theta[1], Theta[2], mse]

In [37]:
assertFloatList(answers['Q2'], 4)

In [ ]:
### Question 3

In [138]:
def feature(datum, deg):
    # feature for a specific polynomial degree
    feat = [1]
    feat.append(datum['review_text'].count("!"))
    if deg >= 2:
        feat.append((datum['review_text'].count("!"))**2)
    if deg >= 3:
        feat.append((datum['review_text'].count("!"))**3)
    if deg >= 4:
        feat.append((datum['review_text'].count("!"))**4)
    if deg >= 5:
        feat.append((datum['review_text'].count("!"))**5)
    return feat

In [145]:
MSEs = []
for i in range(1,6):
    X = numpy.array([feature(d, i) for d in dataset])
    Y = [d['rating'] for d in dataset]
    model = sklearn.linear_model.LinearRegression(fit_intercept=False)
    model.fit(X, Y)
    y_pred = model.predict(X)
    sse = sum([x**2 for x in (Y - y_pred)])
    mse = sse / len(Y)
    MSEs.append(mse)

In [43]:
answers['Q3'] = MSEs

In [44]:
assertFloatList(answers['Q3'], 5)# List of length 5

In [ ]:
### Question 4

In [152]:
train = dataset[:5000]
test = dataset[5000:]

In [151]:
MSEs = []
for i in range(1,6):
    X = numpy.array([feature(d, i) for d in train])
    Y = [d['rating'] for d in train]
    model = sklearn.linear_model.LinearRegression(fit_intercept=False)
    model.fit(X, Y)
    X_test = numpy.array([feature(d, i) for d in test])
    Y_test = [d['rating'] for d in test]
    y_pred = model.predict(X_test)
    sse = sum([x**2 for x in (Y_test - y_pred)])
    mse = sse / len(Y)
    MSEs.append(mse)
MSEs

[1.524874385986712,
 1.4977199259322234,
 1.4856632190311374,
 1.4767337440079402,
 1.4809577272705439]

In [75]:
answers['Q4'] = MSEs

In [76]:
assertFloatList(answers['Q4'], 5)

In [ ]:
### Question 5

In [153]:
Y = [d['rating'] for d in test]
med = statistics.median(Y)
y_pred = [med for d in test]

In [154]:
summation = 0
for i in range(len(Y)):
    summation += abs(Y[i] - y_pred[i])
mae = summation/len(Y)
mae

0.907

In [81]:
answers['Q5'] = mae

In [82]:
assertFloat(answers['Q5'])

In [ ]:
### Question 6

In [2]:
f = open("beer_50000.json")
dataset = []
for l in f:
    if 'user/gender' in l:
        dataset.append(eval(l))

In [109]:
len(dataset)

20403

In [3]:
X = [[1, d['review/text'].count("!")] for d in dataset]
y = [d['user/gender'] == 'Female' for d in dataset]
X[10]

[1, 1]

In [100]:
mod = sklearn.linear_model.LogisticRegression()
mod.fit(X,y)

LogisticRegression()

In [107]:
predictions = mod.predict(X) # Binary vector of predictions
#correct = predictions == y # Binary vector indicating which predictions were correct
#sum(correct) / len(correct)
y[0] == predictions[0]

False

In [114]:
TP = sum([(p and l) for (p,l) in zip(predictions, y)])
FP = sum([(p and not l) for (p,l) in zip(predictions, y)])
TN = sum([(not p and not l) for (p,l) in zip(predictions, y)])
FN = sum([(not p and l) for (p,l) in zip(predictions, y)])

In [116]:
TPR = TP / (TP + FN)
TNR = TN / (TN + FP)
BER = 1 - 1/2 * (TPR + TNR)
BER

0.5

In [117]:
answers['Q6'] = [TP, TN, FP, FN, BER]

In [118]:
assertFloatList(answers['Q6'], 5)

In [ ]:
### Question 7

In [4]:
mod = sklearn.linear_model.LogisticRegression(class_weight='balanced')
mod.fit(X,y)
predictions = mod.predict(X)

In [123]:
TP = sum([(p and l) for (p,l) in zip(predictions, y)])
FP = sum([(p and not l) for (p,l) in zip(predictions, y)])
TN = sum([(not p and not l) for (p,l) in zip(predictions, y)])
FN = sum([(not p and l) for (p,l) in zip(predictions, y)])
TPR = TP / (TP + FN)
TNR = TN / (TN + FP)
BER = 1 - 1/2 * (TPR + TNR)

In [124]:
answers["Q7"] = [TP, TN, FP, FN, BER]

In [125]:
assertFloatList(answers['Q7'], 5)

In [ ]:
### Question 8

In [5]:
probs = mod.predict_proba(X)
probY = list(zip([p[1] for p in probs], [p[1] > 0.5 for p in probs], y))
probY.sort(reverse=True) # Sort data by confidence

In [6]:
precisionList = []
for i in [1, 10, 100, 1000, 10000]:
    labs = [x[2] for x in probY[:i]]
    prec = sum(labs) / len(labs)
    precisionList.append(prec)
precisionList

[0.0, 0.0, 0.03, 0.033, 0.0308]

In [14]:
len(labs[:100])

100

In [135]:
answers['Q8'] = precisionList

In [136]:
assertFloatList(answers['Q8'], 5) #List of five floats

In [137]:
f = open("answers_hw1.txt", 'w') # Write your answers to a file
f.write(str(answers) + '\n')
f.close()